name: Build Android
on:
  push:
    tags:
    - 'v[0-9]+*' 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - run: echo ${{ steps.yq.outputs.result }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.yq.outputs.result }}