name: Build and upload new version
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    name: build_upload
    permissions: write-all
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - name: Check Version
        uses: ./.github/actions/check_verion
        
      - uses: ./.github/actions/build
        with:
          store-base64: ${{ secrets.ANDROID_SIGN_BASE64 }}
          store-pass: ${{ secrets.ANDROID_SIGN_STORE_PASS }}
          key-alias: ${{ secrets.ANDROID_SIGN_ALIAS }}
          key-pass: ${{ secrets.ANDROID_SIGN_KEY_PASS }}
          ios-certificate-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          ios-certificate-password: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ios-provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          ios-keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
          build-apk: false

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.lifetalk.learn.language.speaks
          releaseFiles: ./build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft

      - name: Upload iOS app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: build/ios/ipa/flutter_build.ipa 
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}