name: Build Android
on:
  push:
    tags:
    - 'v[0-9]+*' 

jobs:
  build:
    name: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'
          
      - name: Check equal version
        id: equal
        result: ${{ startsWith("v${{ steps.yq.outputs.result }}", $GITHUB_REF_NAME) }}
        run: echo "${{ steps.yq.outputs.result }} $GITHUB_REF_NAME"

      # - name: Check equals tag with version
      #   if: ${{ steps.equal.result == 'false' }}
      #   run: "echo pubspec version and tag version must be equal "${{ steps.equal.result }}"

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: $GITHUB_REF_NAME