name: Build iOS
on:
  push:
    tags:
    - 'i[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build iOS App
    permissions: write-all
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        # if: steps.check_flutter.outputs.installed == 'false'
        uses: subosito/flutter-action@v2
        with:
          # channel: stable
          flutter-version: '3.19.3'

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --release --export-options-plist=ios/GithubActionsExportOptions.plist
          certificate-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASS }}
          provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
          

      # - name: Upload application
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release.ipa
      #     path: ./build/ios/ipa/flutter_build.ipa

      # - name: Upload iOS app to TestFlight
      #   uses: apple-actions/upload-testflight-build@v1
      #   with: 
      #     app-path: build/ios/ipa/flutter_build.ipa
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}