name: Release Tag
on:
  push:
    tags:
    - 'r[0-9]+*' 

jobs:
  release:
    name: release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      # - name: Get version
      #   id: yq
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq -r '.version' 'pubspec.yaml'
          
      # - name: Get project version
      #   run: echo "PROJECT_VERSION=v${{ steps.yq.outputs.result }}" >> $GITHUB_ENV
        
      - uses: ./.github/actions/build
        with:
          store-base64: ${{ secrets.ANDROID_SIGNING_KEY }}
          store-pass: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          key-pass: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Get version  
        id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml

      - name: Get the tag and remove the first character
        id: get_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG_WITHOUT_FIRST_CHAR=${TAG:1}
          echo "TAG_WITHOUT_FIRST_CHAR=$TAG_WITHOUT_FIRST_CHAR" >> $GITHUB_ENV

      - uses: nick-invision/assert-action@v1
        with:
          expected: ${{ env.TAG_WITHOUT_FIRST_CHAR }}
          actual: ${{ steps.read-version.outputs.version-number }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/app/outputs/apk/release/*.apk,./build/app/outputs/bundle/release/app-release.aab"
          tag: $GITHUB_REF_NAME