name: Release Tag
on:
  push:
    tags:
    - 'u[0-9]+*' 

jobs:
  # build:
  #   name: build
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #   steps:

  #     # - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #       with:
  #         store-base64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #         store-pass: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
  #         key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
  #         key-pass: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
  #         build-apk: false
 
  upload:
    name: Upload app to internal track
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Get appbundle from artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: appbundle
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.lifetalk.learn.language.speaks
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: alpha
          status: completed